@startuml

skinparam shadowing false
skinparam stereotypeCBackgroundColor #5B9BD5
' skinparam backgroundColor transparent

skinparam note {
  BackgroundColor #73AE42
  BorderColor #6CA43E
  FontColor white
}

skinparam class {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #FFFFFF
}

skinparam sequence {
  ArrowColor #6CA43E

  LifeLineBorderColor #6CA43E
  LifeLineBackgroundColor #73AE42

  ParticipantBorderColor #2E75B5
  ParticipantBackgroundColor #5B9BD5

  ActorBorderColor #2E75B5
  ActorBackgroundColor #5B9BD5

  BoxLineColor #A5A5A5
}

skinparam state {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam usecase {
  BackgroundColor #EEEEEE
  BorderColor #9E9E9E

  ArrowColor #6CA43E
  ActorBorderColor #6CA43E
}

skinparam component {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam node {
  BackgroundColor #FFFFFF
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam database {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}
class Diplo.Armees.Armee {
    #casts : array = ["integer", "integer", "integer"]
    #fillable : array = ["id_case"]
    #hidden : array = ["created_at", "updated_at", "id_partie"]
    +caseOccupee() : Illuminate.Database.Eloquent.Relations.HasOne
    +getCase() : Diplo.Cartes.CaseClass
    +getId() : int
    +getJoueur() : Diplo.Joueurs.Joueur
    +getOrdre() : Diplo.Ordres.OrdreModel
    +getOrdres() : OrdreModel[]
    +getProprietaire() : Diplo.Joueurs.Joueur
    +ordre() : Illuminate.Database.Eloquent.Relations.HasOne
    +ordres() : Illuminate.Database.Eloquent.Relations.HasMany
    +proprietaire() : Illuminate.Database.Eloquent.Relations.BelongsTo
}
class Diplo.Armees.Armee extends Illuminate.Database.Eloquent.Model
class Diplo.Armees.EloquentArmeeRepository {
    +deplacerArmee(armee : Diplo.Armees.Armee, case : Diplo.Cartes.CaseInterface)
    +detruireArmee(armee : Diplo.Armees.Armee)
    +trouverParId(id : int) : Armee
}
class Diplo.Armees.EloquentArmeeRepository implements Diplo.Armees.ArmeeRepository
interface Diplo.Armees.ArmeeRepository {
    +deplacerArmee(armee : Diplo.Armees.Armee, case : Diplo.Cartes.CaseInterface)
    +detruireArmee(armee : Diplo.Armees.Armee)
    +trouverParId(id : int) : Armee
}
@enduml
