all: compil clean

compil:
	pdflatex soutenance.tex
	pdflatex soutenance.tex

clean:
	rm -f soutenance.aux
	rm -f soutenance.fdb_latexmk
	rm -f soutenance.log
	rm -f soutenance.nav
	rm -f soutenance.out
	rm -f soutenance.snm
	rm -f soutenance.synctex.gz
	rm -f soutenance.toc
